services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: assistx-test-app
    ports:
      - "8080:8080"
    environment:
      APP_ENV: local
      APP_DEBUG: 1
      APP_KEY: base64:4NMVnG9R7ofvyX/bnQopZASRXj+kCpmbvASd6mpWO7E=
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: assistxdb
      DB_USERNAME: root
      DB_PASSWORD: 7uno12345
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: assistx_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 7uno12345
      MYSQL_DATABASE: assistxdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
