version: "3.8"

services:
  app:
    build: .
    container_name: assistx-test-app
    ports:
      - "8080:8080"
    environment:
      APP_ENV: local
      APP_DEBUG: 1
      APP_KEY: base64:dummykeydummykeydummykeydummykey=
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: assistxdb
      DB_USERNAME: root
      DB_PASSWORD: 7uno12345
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
